spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/otus_spring"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
#        default_schema: library
        format_sql: true
  liquibase:
    change-log: "classpath:db.changelog/changelog-master.sql"